export const keyWords = [
  "lp leaning",
  "AI learning",
  "AI education",
  "AI teaching",
  "AI learning platform",
  "AI learning system",
  "AI learning tools",
  "online learning",
  "AI education",
  "sentiment analysis in learning",
  "machine learning in education",
  "teacher feedback platform",
  "facial expression recognition",
  "learn and share knowledge",
  "student performance analysis",
  "AI monitoring in education",
  "educational technology",
  "teacher tools",
  "student engagement",
  "e-learning",
  "online teaching platform",
  "knowledge sharing platform",
  "personalized learning",
  "education innovation",
  "advanced AI in education",
  "learning feedback system",
  "edtech platform",
  "online courses",
  "virtual classrooms",
  "AI-driven education tools",
  "remote learning",
  "distance education",
  "educational software",
  "online training programs",
  "blended learning",
  "interactive learning platforms",
  "gamified education",
  "digital learning tools",
  "adaptive learning technologies",
  "virtual learning environments",
  "best online learning platforms",
  "AI-powered assessments",
  "AI-enabled teaching tools",
  "real-time feedback in education",
  "AI-based performance tracking",
  "education technology solutions",
  "teacher training software",
  "student engagement strategies",
  "remote education solutions",
  "AI for teachers",
  "machine learning in teaching",
  "AI in higher education",
  "personalized learning experiences",
  "AI monitoring software",
  "learning analytics tools",
  "student performance tracking",
  "data-driven education",
  "AI-driven analytics in learning",
  "intelligent tutoring systems",
  "online education solutions",
  "e-learning innovations",
  "advanced learning technologies",
  "school management systems",
  "smart education platforms",
  "AI in edtech",
  "AI for schools",
  "learning experience platforms",
  "AI-powered course creation",
  "AI-enhanced learning outcomes",
  "automated teaching assistants",
  "online education programs",
  "knowledge dissemination platforms",
  "AI tools for students",
  "teaching feedback systems",
  "AI in K-12 education",
  "remote learning software",
  "teacher support tools",
  "educational innovation platforms",
  "edtech startups",
  "next-gen learning tools",
  "gamification in online education",
  "student monitoring tools",
  "AI-based learning platforms",
  "adaptive education systems",
  "intelligent learning systems",
  "education AI research",
  "digital classrooms",
  "AI for student engagement",
  "virtual reality in education",
  "facial expression analysis in learning",
  "AI-enabled student feedback",
  "remote education platforms",
  "innovative teaching methods",
  "AI solutions for education",
  "advanced digital learning tools",
  "personalized student assessments",
  "virtual tutoring platforms",
  "best online teaching tools",
  "AI-powered educational tools",
  "education technology for schools",
  "AI in online learning",
  "AI-driven learning platforms",
  "interactive online education",
  "remote teaching solutions",
  "AI in professional development",
  "student progress analysis",
  "education AI startups",
  "AI-enhanced classroom tools",
  "smart teaching platforms",
  "learning technology trends",
  "online collaboration tools for students",
  "adaptive learning environments",
  "virtual education platforms",
  "real-time analytics in education",
  "AI-driven teaching systems",
  "student behavior analysis",
  "AI-based classroom tools",
  "digital education trends",
  "next-generation edtech",
  "AI-enhanced teacher training",
  "school technology solutions",
  "intelligent education systems",
  "virtual learning solutions",
  "AI-supported learning outcomes",
  "education technology products",
  "interactive student engagement tools",
  "gamification platforms for education",
  "online course management",
  "AI-driven tutoring systems",
  "learning data analytics",
  "personalized learning platforms",
  "advanced learning tools",
  "edtech for teachers",
  "online course creation platforms",
  "best AI education tools",
  "digital education software",
  "learning management platforms",
  "AI-powered learning analytics",
  "performance tracking in education",
  "AI in academic assessments",
  "education data tools",
  "AI-based study tools",
  "learning personalization technologies",
  "automated student monitoring",
  "AI in school administration",
  "AI for curriculum development",
  "adaptive e-learning tools",
  "learning optimization platforms",
  "AI tools for academic success",
  "best platforms for online learning",
  "digital innovation in education",
  "advanced e-learning tools",
  "learning feedback platforms",
  "school management platforms",
  "educational AI analytics",
  "virtual learning systems",
  "real-time feedback tools",
  "AI for teacher improvement",
  "personalized education solutions",
  "online education analytics",
  "education platform innovations",
  "teaching technology advancements",
  "digital education innovations",
  "AI solutions for teachers",
  "interactive learning methods",
  "advanced education research",
  "remote classroom solutions",
  "e-learning optimization tools",
  "AI for academic growth",
  "learning improvement platforms",
  "AI-driven classroom tools",
  "innovative education technology",
  "student-centered learning tools",
  "AI-powered feedback mechanisms",
  "teaching improvement platforms",
  "virtual classroom engagement",
  "best teaching platforms",
  "AI-assisted education systems",
  "real-time learning analytics",
  "AI-based study platforms",
  "digital teaching aids",
  "AI-powered educational platforms",
  "school improvement tools",
  "next-gen online education",
  "virtual education technologies",
  "AI in academic research",
  "AI-assisted student engagement",
  "AI-based teacher tools",
  "innovative edtech solutions",
  "personalized learning tools",
  "virtual learning tools",
  "gamified teaching platforms",
  "learning environment technologies",
  "education data platforms",
  "AI for better learning",
  "education personalization systems",
  "AI for education technology",
  "advanced school tools",
  "interactive teaching aids",
  "AI-driven knowledge sharing",
  "learning systems for schools",
  "education AI platforms",
  "advanced teaching aids",
  "digital tools for learning",
  "edtech learning platforms",
  "AI in digital classrooms",
  "AI-powered education solutions",
  "gamification in teaching",
  "real-time AI feedback",
  "educational analytics platforms",
  "AI-powered learning systems",
  "teacher training innovations",
  "student-focused education tools",
  "next-generation teaching aids",
  "advanced learning systems",
  "remote education innovations",
  "AI-powered knowledge platforms",
  "AI for improving education",
  "education transformation tools",
  "AI-enhanced student learning",
  "AI-driven curriculum tools",
  "online teaching innovations",
  "learning experience innovations",
  "best tools for online education",
  "AI-based education software",
  "virtual classroom tools",
  "AI for improving teaching",
  "real-time student assessments",
  "AI in school learning",
  "next-gen education systems",
  "intelligent learning analytics",
  "AI-enhanced study tools",
  "online learning innovations",
  "edtech advancements",
  "AI for smarter education",
  "next-generation learning tools",
  "adaptive education tools",
  "AI solutions for online education",
  "digital learning innovations",
  "student-focused learning platforms",
  "learning analytics solutions",
  "AI-powered edtech platforms",
  "education analytics tools",
  "online learning personalization",
  "AI-powered student platforms",
  "education improvement platforms",
  "digital tools for teachers",
  "interactive education systems",
  "school-focused edtech",
];
